# Data Loading, Storage

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# You have to upload the data by using the Files function on your dashboard

## Reading and Writing Data in Text Format

Two methods:
- *read_csv*: Read a comma-separated values (csv) file into DataFrame. Also supports optionally iterating or breaking of the file into chunks.
- *to_csv*: Write object to a comma-separated values (csv) file.

### Reading Text Files

In [3]:
!cat "data/ex1.csv"

,a,b,c,d,message
0,1,2,3,4,hello
1,5,6,7,8,world
2,9,10,11,12,foo

In [5]:
df= pd.read_csv("data/ex1.csv", sep=',')
df

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [ ]:
type(df)

define separator value and header

In [ ]:
# define the table sepator value

df = pd.read_csv('ex1.csv', sep='\t')
df

In [ ]:
 !cat "ex2.csv"

In [ ]:
# define if the table header exists

pd.read_csv('ex2.csv', sep=',', header=None)

define column name and/or index name

In [ ]:
# define column name

pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

In [ ]:
# define index name

names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('ex2.csv', names=names, index_col='message')

you can skip a list of row

In [6]:
!cat "data/ex4.csv"

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [8]:
pd.read_csv('data/ex4.csv', sep=',')

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [10]:
# you can skip a list of row
pd.read_csv('data/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
!cat ex5.csv

In [ ]:
result = pd.read_csv('ex5.csv')
result

In [ ]:
pd.isnull(result)

define *na_values*

In [ ]:
result = pd.read_csv('ex5.csv', na_values=['one', 'foo']) # na_values means values to substitute with NaN
result

In [ ]:
sentinels = {'message': ['foo'], 'something': ['two']}
pd.read_csv('ex5.csv', na_values=sentinels)

### Reading Text Files in Pieces

In [ ]:
result = pd.read_csv('ex6.csv')
result

Read only a fixed number of rows

In [ ]:
pd.read_csv('ex6.csv', nrows=5)

Read Text Files in chunks

In [ ]:
chunker = pd.read_csv('ex6.csv', chunksize=1000)
chunker

In [ ]:
chunk = next(chunker) #dataframe with other 1000 rows 
chunk.head(5)

In [ ]:
for i, chunk in enumerate(chunker):
  print("chunk #{} size: {}".format(i, chunk.shape))

### Writing Data to Text Format

In [ ]:
data = pd.read_csv('ex5.csv')
data

In [ ]:
data.iloc[0,0] = 999

In [ ]:
data

In [ ]:
data.to_csv('out.csv')

In [ ]:
!cat out.csv

In [ ]:
data.to_csv('out.csv',index=False)

In [ ]:
!cat out.csv

In [ ]:
pd.read_csv('out.csv', sep=',')

In [ ]:
data.to_csv('out.csv', index=False, sep='#')

In [ ]:
!cat out.csv

In [ ]:
pd.read_csv('out.csv', sep='#')

### Reading and Writing Microsoft Excel Files

Read option 1: Using *ExcelFile* class

In [ ]:
xlsx = pd.ExcelFile('ex1.xlsx')

In [ ]:
xlsx

Read option 2: Using *read_excel* method

In [ ]:
pd.read_excel(xlsx, 'Sheet1')

In [ ]:
frame = pd.read_excel('ex1.xlsx', 'Sheet1')
frame

Write option 1: using *ExcelWriter* object

In [ ]:
writer = pd.ExcelWriter('ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

Write option 2: using *to_excel* method

In [ ]:
frame

In [ ]:
frame.to_excel('ex2_out.xlsx')

### Optional: Working with Delimited Formats

In [ ]:
!cat ex7.csv

In [ ]:
import csv
f = open('ex7.csv')

reader = csv.reader(f)

In [ ]:
for line in reader:
    print(line)

In [ ]:
with open('ex7.csv') as f:
    lines = list(csv.reader(f))

In [ ]:
header, values = lines[0], lines[1:]

In [ ]:
header

In [ ]:
values

In [ ]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

## Optional

In [ ]:
with open('ex3.txt', 'r') as f:
  lines = f.readlines()
lines

In [ ]:
columns = [val.strip() for val in lines[0].split(' ') if val != '']
columns

In [ ]:
data = []
for row in lines[1:]:
  res = [val.strip() for val in row.split(' ') if val != ''] # strip = trim
  data.append(res)

In [ ]:
data

In [ ]:
columns

In [ ]:
columns.insert(0, 'index')
columns

In [ ]:
ds = pd.DataFrame(data, columns=columns)
ds

In [ ]:
ds.set_index('index')